pipeline {
  agent any

  parameters {
    string(
      name: 'IMAGE_TAG',
      defaultValue: 'stable',
      description: 'Enter Docker image tag to deploy'
    )
  }

  environment {
    HELM_RELEASE = "new-nginx"
    HELM_CHART   = "./deploy/my-nginx"
  }

  stages {

    stage('Clone Repository') {
      steps {
        git branch: 'main',
            url: 'https://github.com/sandipkhot96-ops/Ngnix-Sandip.git'
      }
    }

    stage('Deploy using Helm') {
  steps {
    sh """
      echo "Deploying custom image: sandipkhot96/custom-nginx:1.0"
      helm upgrade --install ${HELM_RELEASE} ${HELM_CHART} \
        --set image.repository=sandipkhot96/custom-nginx \
        --set image.tag=1.0 \
        -n jenkins --wait
    """
  }
}

    stage('Verify Deployment') {
      steps {
        sh '''
           kubectl get pods -n jenkins
           kubectl get svc -n jenkins
          
        '''
      }
    }

  }
}
