name: Build and Deploy NGINX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t sandipkhot96/nginx-sandip:gha-${{ github.run_number }} .

      - name: Push to Docker Hub
        run: |
          docker push sandipkhot96/nginx-sandip:gha-${{ github.run_number }}

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with Helm
        run: |
          helm upgrade --install new-nginx ./deploy/my-nginx \
            --namespace jenkins \
            --set image.repository=sandipkhot96/nginx-sandip \
            --set image.tag=gha-${{ github.run_number }}
